import java.sql.*;

import javax.swing.JOptionPane;
import mns.ConnectionProvider;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mulan
 */
public class AlertChecker extends javax.swing.JFrame {
    
    
    /**
     * Creates new form AlertChecker
     */
    public AlertChecker() {
        initComponents();
    }

    

    private void checkAlerts() {
        String[] columnNames = {"Medicine Name", "Quantity", "EXP Date", "Alert Type"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        rtable.setModel(model);
        checkExpiryAlerts(model);
        checkLowStockAlerts(model);
    }

    private void checkExpiryAlerts(DefaultTableModel model) {
    String query = "SELECT name, quantity, edate FROM medicine WHERE edate <= DATE_ADD(CURDATE(), INTERVAL 30 DAY)";
    try {
        Connection con = ConnectionProvider.getCon();
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date todayPlus30 = new java.util.Date(System.currentTimeMillis() + 30L * 24 * 60 * 60 * 1000);

        

        while (rs.next()) {
            String name = rs.getString("name");
            int quantity = rs.getInt("quantity");
            String edateStr = rs.getString("edate");

            java.util.Date edate = sdf.parse(edateStr);

            if (edate.before(todayPlus30)) {
                model.addRow(new Object[]{name, quantity, sdf.format(edate), "Expiring Soon"});

            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Expiry Alert Error: " + e.getMessage());
    }
}


    private void checkLowStockAlerts(DefaultTableModel model) {
        String query = "SELECT name, quantity FROM medicine WHERE quantity < 10";
         try {
        Connection con = (Connection) ConnectionProvider.getCon();
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        
        
        while (rs.next()) {
            String name = rs.getString("name");
            int quantity = rs.getInt("quantity");

            model.addRow(new Object[]{name, quantity, "", "Low Stock"});
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Low Stock Alert Error: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCheckAlerts = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Medicine Alert Checker");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 12, -1, -1));

        btnCheckAlerts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheckAlerts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnCheckAlerts.setText("Check Alerts");
        btnCheckAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAlertsActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckAlerts, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 102, -1, -1));

        rtable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Quantity", "EXP Date", "Alert Type"
            }
        ));
        jScrollPane1.setViewportView(rtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 658, 290));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, 881, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, 29));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAlertsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)rtable.getModel();
        model.setRowCount(0);
        checkExpiryAlerts(model);
        checkLowStockAlerts(model);
    }//GEN-LAST:event_btnCheckAlertsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlertChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlertChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlertChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlertChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlertChecker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAlerts;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable rtable;
    // End of variables declaration//GEN-END:variables
}
